spring:
  profiles:
    active: dev
  datasource:
    url: "${DATASOURCE_URL: jdbc:postgresql://localhost:5432/SecretSanta}"
    username: "${DATASOURCE_USERNAME: db_user}"
    password: "${DATASOURCE_PASSWORD: db_password}"
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
    open-in-view: false
    platform: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          token-info-uri: "${OAUTH_URL: https://cognito-idp.amazonaws.com/us-east-1}"

security:
  basic:
    enabled: false

management:
  endpoint:
    info:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

#logging:
#  level:
#    web: TRACE
#    org:
#      springframework:
#        web: TRACE
