name: Docker Image CI

on:
  workflow_run:
    workflows: [ "Java CI with Maven" ]
    branches: [ "develop" ]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: mvn spring-boot:build-image -DskipTests
      #docker build . --file Dockerfile --tag secret-santa-api:$(date +%s)
